version: '2'

services:

    host:
        container_name: host-a
        build: docker
        cap_add:
            - NET_ADMIN
            - NET_BROADCAST

networks:

    default:
        external:
            name: ha-container-network
